// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using Microsoft.ML.Data;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using AutoMapper;
using AI_Server.Mapping;
using AI_Server.DTOs.MoodModel;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<MoodModel.ModelInput, MoodModel.ModelOutput>()
    .FromFile("Service/MoodModel.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddAutoMapper(m => m.AddProfile(typeof(MappingProfile)));

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
    });
}


// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<MoodModel.ModelInput, MoodModel.ModelOutput> predictionEnginePool, MoodModel.ModelInput input, IMapper _mapper) =>
        await Task.FromResult(_mapper.Map<MoodModelOutDTO>(predictionEnginePool.Predict(input))));

// Run app
app.Run();
